
version: '3.9'
services:
  cita-frontend-app:
    image: selimhorri/cita-frontend-app
    container_name: cita-frontend-app
    ports:
      - 4200:80
    restart: always
#    depends_on:
#      - cita-backend-app
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - net

networks:
  net:
    external:
      name: cita-net





