
apiVersion: v1
kind: Namespace
metadata:
  name: cita-preprod-ns

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: cita-frontend-app-deployment
  namespace: cita-preprod-ns
  labels:
    app: cita-frontend-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cita-frontend-app
  template:
    metadata:
      labels:
        app: cita-frontend-app
    spec:
      containers:
        - name: cita-frontend-app
          image: selimhorri/cita-frontend-app:staging
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
          - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: cita-frontend-app-service
  namespace: cita-preprod-ns
spec:
  selector:
    app: cita-frontend-app
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 4200
      targetPort: 80
      nodePort: 30000







